services:
  agent-frontend:
    container_name: agent-frontend
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "4200:4200"
    networks:
      - agent-net
    restart: always

networks:
  agent-net:
    driver: bridge
